# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: kitchen-opensuse-153
'on':
  pull_request: ~
  push:
    branches:
      - master

jobs:
  kitchen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'

      - name: Install bundler
        run: gem install bundler

      - name: Install kitchen
        run: bundle install

      - name: Kitchen default
        run: bin/kitchen test default-opensuse-leap-153-master-py3

      - name: Kitchen auth
        run: bin/kitchen test auth-opensuse-leap-153-master-py3
